In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
df = pd.read_csv("C:/Users/Odunayo Grace/Desktop/Backup files/Desktop/2024 GROWTH/HAMOYE DATA SCIENCE INTERNSHIP_Must_complete/Classification and logistics readings/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [27]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [28]:
# Convert column 'TotalCharges' to numeric, setting invalid parsing as NaN
df["TotalCharges"] = pd.to_numeric(df['TotalCharges'], errors='coerce')
#df['TotalCharges']

In [29]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [30]:
df = df.fillna(0)

In [31]:
#df.isnull().sum()

In [32]:
#Converting to binary values
# Map 'yes' to 1 and 'no' to 0
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

# Display the DataFrame after conversion
#print("\nDataFrame after conversion:")
#print(df)

In [33]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [34]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [35]:
#df = df.drop(columns=[ "customerID", "gender",  "SeniorCitizen", "Partner", "Dependents"])
X = df.drop(columns= 'Churn' ) #feature
y = df[ 'Churn' ] #target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2 , random_state= 1)
y_train.value_counts()

Churn
0    4113
1    1521
Name: count, dtype: int64

In [36]:
categorical = ["gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod"]
numerical = ["tenure", "MonthlyCharges", "TotalCharges"]

In [37]:
#Feaure engineering
from sklearn.preprocessing import StandardScaler
numerical = ["tenure", "MonthlyCharges", "TotalCharges"]
scaler = StandardScaler()
scaled_numerical = scaler.fit_transform(df[numerical])
scaled_numerical_df = pd.DataFrame(scaled_numerical, columns=numerical)

# Step 5: Combine scaled numerical features with the rest of the original DataFrame
# Drop original numerical columns and concatenate the scaled ones
data_scaled = df.drop(columns=numerical).join(scaled_numerical_df)
#print(data_scaled)

In [38]:
from sklearn.preprocessing import OneHotEncoder
categorical = ["gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod"]
# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse=False, drop='first')  # drop='first' to avoid dummy variable trap
# Fit and transform the encoder on the categorical columns
encoded_array = encoder.fit_transform(df[categorical])
# Get the new column names after encoding
encoded_columns = encoder.get_feature_names_out(categorical)
# Convert the encoded array back to a DataFrame
encoded_df = pd.DataFrame(encoded_array, columns=encoded_columns)
# Drop the original categorical columns from the original DataFrame
df.drop(columns=categorical, inplace=True)
# Concatenate the original DataFrame (without the categorical columns) and the encoded DataFrame
df_final = pd.concat([df.reset_index(drop=True), encoded_df.reset_index(drop=True)], axis=1)
#print(df_final)

C:\Users\Odunayo Grace\.spss\Anaconda1\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [39]:
df_final.head()

,customerID,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,1,29.85,29.85,0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,5575-GNVDE,34,56.95,1889.50,0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,3668-QPYBK,2,53.85,108.15,1,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,7795-CFOCW,45,42.30,1840.75,0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,9237-HQITU,2,70.70,151.65,1,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [40]:
x = df_final.drop(columns= ["customerID", "Churn"]) #feature
y = df_final[ 'Churn' ] #target
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2 , random_state= 1)
y_train.value_counts()

Churn
0    4113
1    1521
Name: count, dtype: int64

In [41]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


# Initialize the models with random_state=1
rf_clf = RandomForestClassifier(random_state=1)
et_clf = ExtraTreesClassifier(random_state=1)
xgb_clf = XGBClassifier(random_state=1, use_label_encoder=False, eval_metric='logloss')
lgbm_clf = LGBMClassifier(random_state=1)

# Train the models
rf_clf.fit(x_train, y_train)
et_clf.fit(x_train, y_train)
xgb_clf.fit(x_train, y_train)
lgbm_clf.fit(x_train, y_train)

# Predict on the test set
y_pred_rf = rf_clf.predict(x_test)
y_pred_et = et_clf.predict(x_test)
y_pred_xgb = xgb_clf.predict(x_test)
y_pred_lgbm = lgbm_clf.predict(x_test)

# Evaluate the models
print("Random Forest Classifier:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf)}")
print(classification_report(y_test, y_pred_rf))

print("Extra Trees Classifier:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_et)}")
print(classification_report(y_test, y_pred_et))

print("XGBoost Classifier:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_xgb)}")
print(classification_report(y_test, y_pred_xgb))

print("LightGBM Classifier:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_lgbm)}")
print(classification_report(y_test, y_pred_lgbm))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1521, number of negative: 4113
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000778 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 637
[LightGBM] [Info] Number of data points in the train set: 5634, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.269968 -> initscore=-0.994785
[LightGBM] [Info] Start training from score -0.994785
Random Forest Classifier:
Accuracy: 0.801277501774308
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1061
           1       0.61      0.56      0.58       348

    accuracy                           0.80      1409
   macro avg       0.73      0.72      0.73      1409
weighted avg       0.80      0.80      0.80      1409

Extra Trees Classifier:
Accuracy: 0.7828246983676366
              precision    recall  f1-score   support

           0       0.84      0.87      0.86      1061
           1       0.57      0.51      0.54       348

    accuracy                           0.78      1409
   macro avg       0.71      0.69      0.70      1409
weighted avg       0.78      0.78      0.78      1409

XGBoost Classifier:
Accuracy: 0.7991483321504613
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1061
           1       0.60      0.57      0.58       348

    accuracy                           0.80      1409
   macro avg       0.73      0.72      0.72      1409
weighted avg       0.80      0.80      0.80      1409

LightGBM Classifier:
Accuracy: 0.808374733853797
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1061
           1       0.62      0.58      0.60       348

    accuracy                           0.81      1409
   macro avg       0.74      0.73      0.74      1409
weighted avg       0.80      0.81      0.81      1409